### ISSUE TITLE
CapacityError

### ISSUE THREAD

**Issue by LastBreeze** [rust-av/grav1synth#8]
I'm getting this error on all aomenc encodes (haven't tested on svt/rav1e)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.7.2/src/arrayvec_impl.rs:39:32
If you need a rust backtrace, let me know what command to use.

**Comment by shssoichiro** [comment]
Thanks for filing this. If you add the env var `RUST_BACKTRACE=1` to the command then Rust will print out a full backtrace.

**Comment by LastBreeze** [comment]
Here's my prompt reply :)

RUST_BACKTRACE=1 grav1synth generate my_encode.mkv -o grainy_encode.mkv --iso 1200 --chroma
File grainy_encode.mkv exists. Overwrite? yes
[libdav1d @ 0x5603822240c0] libdav1d 1.0.0
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 6 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 7 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 8 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 9 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 10 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 11 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5603821c3c80] Could not find codec parameters for stream 12 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[libdav1d @ 0x56038244bec0] libdav1d 1.0.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.7.2/src/arrayvec_impl.rs:39:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: arrayvec::arrayvec::ArrayVec<T,_>::push
   4: grav1synth::parser::grain::film_grain_params
   5: grav1synth::parser::frame::<impl grav1synth::parser::BitstreamParser<_>>::parse_frame_header
   6: grav1synth::parser::obu::<impl grav1synth::parser::BitstreamParser<_>>::parse_obu
   7: grav1synth::parser::BitstreamParser<_>::modify_grain_headers
   8: grav1synth::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

RUST_BACKTRACE=full grav1synth generate my_encode.mkv -o grainy_encode.mkv --iso 1200 --chroma
File grainy_encode.mkv exists. Overwrite? yes
[libdav1d @ 0x55cd931010c0] libdav1d 1.0.0
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 6 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 7 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 8 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 9 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 10 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 11 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55cd930a0c80] Could not find codec parameters for stream 12 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[libdav1d @ 0x55cd93328ec0] libdav1d 1.0.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.7.2/src/arrayvec_impl.rs:39:32
stack backtrace:
   0:     0x55cd92f810ec - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cd92f810ec - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cd92f810ec - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55cd92f810ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cd92e4c23e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x55cd92f7e633 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x55cd92f80eb5 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55cd92f80eb5 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55cd92f8264d - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x55cd92f823b4 - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x55cd92f82cf1 - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x55cd92f82a96 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x55cd92f8162e - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55cd92f827d2 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x55cd92dc4b53 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x55cd92dc4fe3 - core::result::unwrap_failed::h62abf61e411aaa08
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
  16:     0x55cd92e975ec - arrayvec::arrayvec::ArrayVec<T,_>::push::ha27944df1d3cef29
  17:     0x55cd92eacf8d - grav1synth::parser::grain::film_grain_params::h6356b990e2112b70
  18:     0x55cd92ea66d4 - grav1synth::parser::frame::<impl grav1synth::parser::BitstreamParser<_>>::parse_frame_header::h81185546e6cd4f20
  19:     0x55cd92eb2bbe - grav1synth::parser::obu::<impl grav1synth::parser::BitstreamParser<_>>::parse_obu::hb837c3ad3eadda8f
  20:     0x55cd92eb8d06 - grav1synth::parser::BitstreamParser<_>::modify_grain_headers::h694e34b4e6d90eca
  21:     0x55cd92ebb9ce - grav1synth::main::hfeb7be086655bcbd
  22:     0x55cd92e7e9c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5010c259a6fce4e6
  23:     0x55cd92e7eced - std::rt::lang_start::{{closure}}::h430ab8407d33430d
  24:     0x55cd92f79a5f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  25:     0x55cd92f79a5f - std::panicking::try::do_call::h0497133ebe1341e5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  26:     0x55cd92f79a5f - std::panicking::try::h6c3de05c7ca5d07f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  27:     0x55cd92f79a5f - std::panic::catch_unwind::h969058ecb5334b30
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  28:     0x55cd92f79a5f - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  29:     0x55cd92f79a5f - std::panicking::try::do_call::h77301dcf43953993
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  30:     0x55cd92f79a5f - std::panicking::try::h45b05523a2fe135a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  31:     0x55cd92f79a5f - std::panic::catch_unwind::hd95cea544b2b9bd2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  32:     0x55cd92f79a5f - std::rt::lang_start_internal::hd16e6ff7bf05a444
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  33:     0x55cd92ed0aa5 - main
  34:     0x7fb3819cb290 - <unknown>
  35:     0x7fb3819cb34a - __libc_start_main
  36:     0x55cd92dca735 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  37:                0x0 - <unknown>
