### ISSUE TITLE
inspect no worky

### ISSUE THREAD

**Issue by Bubblemint864** [rust-av/grav1synth#9]
```
thread 'main' panicked at 'range start index 18446744073709551615 out of range for slice of length 410174', library\core\src\slice\index.rs:52:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
running inspect on every video I tested on gives me this

**Comment by Quackdoc** [comment]
can you run it with `RUST_BACKTRACE=1` and dump the output

**Comment by Bubblemint864** [comment]
I didn't get much with 1 so here is full:
thread 'main' panicked at 'range start index 18446744073709551615 out of range for slice of length 533850', library\core\src\slice\index.rs:52:5
stack backtrace:
   0:     0x7ff6d9a45f42 - <unknown>
   1:     0x7ff6d9a3d510 - <unknown>
   2:     0x7ff6d98e893b - <unknown>
   3:     0x7ff6d9a32c11 - <unknown>
   4:     0x7ff6d9a223fe - <unknown>
   5:     0x7ff6d9a22e56 - <unknown>
   6:     0x7ff6d9a3de0e - <unknown>
   7:     0x7ff6d9a3d911 - <unknown>
   8:     0x7ff6d9a22b43 - <unknown>
   9:     0x7ff6d98e1c25 - <unknown>
  10:     0x7ff6d98eb98b - <unknown>
  11:     0x7ff6d98eb6b9 - <unknown>
  12:     0x7ff6d98eb6f9 - <unknown>
  13:     0x7ff6d98eb909 - <unknown>
  14:     0x7ff6d9958627 - <unknown>
  15:     0x7ff6d99639a6 - <unknown>
  16:     0x7ff6d9926206 - <unknown>
  17:     0x7ff6d9926d30 - <unknown>
  18:     0x7ff6d9a1f2d8 - <unknown>
  19:     0x7ff6d997a298 - <unknown>
  20:     0x7ff6d98613ae - <unknown>
  21:     0x7ff6d98614e6 - <unknown>
  22:     0x7ff97b5d7614 - <unknown>
  23:     0x7ff97c3626a1 - <unknown>
